sudo: required # superuser permission
services:
  - docker

before_install:
  - docker build -t egeda9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true egeda9/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-671465625855"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"