sudo: required # superuser permission
services:
  - docker

before_install:
  - docker build -t egeda9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true egeda9/docker-react npm run test -- --coverage